// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package offcpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type offcpuBlockedKey struct {
	_       structs.HostLayout
	Tid     uint32
	StackId int32
}

type offcpuStatSlot uint32

const (
	offcpuStatSlotSTAT_EVENTS_DROPPED offcpuStatSlot = 0
	offcpuStatSlotSTAT_TARGETS_FULL   offcpuStatSlot = 1
	offcpuStatSlotSTAT_CGROUPS_FULL   offcpuStatSlot = 2
	offcpuStatSlotSTAT_STACKS_LOST    offcpuStatSlot = 3
	offcpuStatSlotSTAT__MAX           offcpuStatSlot = 4
)

type offcpuThread struct {
	_                  structs.HostLayout
	FirstSeenNs        uint64
	SinceNs            uint64
	OnCpuNs            uint64
	RunqueueNs         uint64
	BlockedNs          uint64
	ThrottledNs        uint64
	UnknownNs          uint64
	CgroupId           uint64
	ThrottleSnapshotNs uint64
	BlockStackId       int32
	State              uint32
	Tid                uint32
	Tgid               uint32
	Comm               [16]int8
}

type offcpuThrottle struct {
	_        structs.HostLayout
	TotalNs  uint64
	SinceNs  uint64
	Episodes uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	offcpuMapBlockedBy           = "blocked_by"
	offcpuMapStacks              = "stacks"
	offcpuMapStats               = "stats"
	offcpuMapTargets             = "targets"
	offcpuMapThreads             = "threads"
	offcpuMapThrottled           = "throttled"
	offcpuProgOnSchedProcessExit = "on_sched_process_exit"
	offcpuProgOnSchedProcessFork = "on_sched_process_fork"
	offcpuProgOnSchedSwitch      = "on_sched_switch"
	offcpuProgOnSchedWakeup      = "on_sched_wakeup"
	offcpuProgOnSchedWakeupNew   = "on_sched_wakeup_new"
	offcpuProgOnThrottleCfsRq    = "on_throttle_cfs_rq"
	offcpuProgOnUnthrottleCfsRq  = "on_unthrottle_cfs_rq"
	offcpuVarFilterTargets       = "filter_targets"
	offcpuVarUnusedBlockedKey    = "unused_blocked_key"
	offcpuVarUnusedStatSlot      = "unused_stat_slot"
	offcpuVarUnusedThread        = "unused_thread"
	offcpuVarUnusedThrottle      = "unused_throttle"
)

// loadOffcpu returns the embedded CollectionSpec for offcpu.
func loadOffcpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OffcpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load offcpu: %w", err)
	}

	return spec, err
}

// loadOffcpuObjects loads offcpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*offcpuObjects
//	*offcpuPrograms
//	*offcpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOffcpuObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOffcpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// offcpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuSpecs struct {
	offcpuProgramSpecs
	offcpuMapSpecs
	offcpuVariableSpecs
}

// offcpuProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuProgramSpecs struct {
	OnSchedProcessExit *ebpf.ProgramSpec `ebpf:"on_sched_process_exit"`
	OnSchedProcessFork *ebpf.ProgramSpec `ebpf:"on_sched_process_fork"`
	OnSchedSwitch      *ebpf.ProgramSpec `ebpf:"on_sched_switch"`
	OnSchedWakeup      *ebpf.ProgramSpec `ebpf:"on_sched_wakeup"`
	OnSchedWakeupNew   *ebpf.ProgramSpec `ebpf:"on_sched_wakeup_new"`
	OnThrottleCfsRq    *ebpf.ProgramSpec `ebpf:"on_throttle_cfs_rq"`
	OnUnthrottleCfsRq  *ebpf.ProgramSpec `ebpf:"on_unthrottle_cfs_rq"`
}

// offcpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuMapSpecs struct {
	BlockedBy *ebpf.MapSpec `ebpf:"blocked_by"`
	Stacks    *ebpf.MapSpec `ebpf:"stacks"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
	Targets   *ebpf.MapSpec `ebpf:"targets"`
	Threads   *ebpf.MapSpec `ebpf:"threads"`
	Throttled *ebpf.MapSpec `ebpf:"throttled"`
}

// offcpuVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuVariableSpecs struct {
	FilterTargets    *ebpf.VariableSpec `ebpf:"filter_targets"`
	UnusedBlockedKey *ebpf.VariableSpec `ebpf:"unused_blocked_key"`
	UnusedStatSlot   *ebpf.VariableSpec `ebpf:"unused_stat_slot"`
	UnusedThread     *ebpf.VariableSpec `ebpf:"unused_thread"`
	UnusedThrottle   *ebpf.VariableSpec `ebpf:"unused_throttle"`
}

// offcpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuObjects struct {
	offcpuPrograms
	offcpuMaps
	offcpuVariables
}

func (o *offcpuObjects) Close() error {
	return _OffcpuClose(
		&o.offcpuPrograms,
		&o.offcpuMaps,
	)
}

// offcpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuMaps struct {
	BlockedBy *ebpf.Map `ebpf:"blocked_by"`
	Stacks    *ebpf.Map `ebpf:"stacks"`
	Stats     *ebpf.Map `ebpf:"stats"`
	Targets   *ebpf.Map `ebpf:"targets"`
	Threads   *ebpf.Map `ebpf:"threads"`
	Throttled *ebpf.Map `ebpf:"throttled"`
}

func (m *offcpuMaps) Close() error {
	return _OffcpuClose(
		m.BlockedBy,
		m.Stacks,
		m.Stats,
		m.Targets,
		m.Threads,
		m.Throttled,
	)
}

// offcpuVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuVariables struct {
	FilterTargets    *ebpf.Variable `ebpf:"filter_targets"`
	UnusedBlockedKey *ebpf.Variable `ebpf:"unused_blocked_key"`
	UnusedStatSlot   *ebpf.Variable `ebpf:"unused_stat_slot"`
	UnusedThread     *ebpf.Variable `ebpf:"unused_thread"`
	UnusedThrottle   *ebpf.Variable `ebpf:"unused_throttle"`
}

// offcpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuPrograms struct {
	OnSchedProcessExit *ebpf.Program `ebpf:"on_sched_process_exit"`
	OnSchedProcessFork *ebpf.Program `ebpf:"on_sched_process_fork"`
	OnSchedSwitch      *ebpf.Program `ebpf:"on_sched_switch"`
	OnSchedWakeup      *ebpf.Program `ebpf:"on_sched_wakeup"`
	OnSchedWakeupNew   *ebpf.Program `ebpf:"on_sched_wakeup_new"`
	OnThrottleCfsRq    *ebpf.Program `ebpf:"on_throttle_cfs_rq"`
	OnUnthrottleCfsRq  *ebpf.Program `ebpf:"on_unthrottle_cfs_rq"`
}

func (p *offcpuPrograms) Close() error {
	return _OffcpuClose(
		p.OnSchedProcessExit,
		p.OnSchedProcessFork,
		p.OnSchedSwitch,
		p.OnSchedWakeup,
		p.OnSchedWakeupNew,
		p.OnThrottleCfsRq,
		p.OnUnthrottleCfsRq,
	)
}

func _OffcpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpu_bpfel.o
var _OffcpuBytes []byte
