// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package netlat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netlatDestStats struct {
	_       structs.HostLayout
	Count   uint64
	TotalNs uint64
	MaxNs   uint64
	Slots   [32]uint64
}

type netlatDestination struct {
	_     structs.HostLayout
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type netlatInFlight struct {
	_      structs.HostLayout
	To     netlatDestination
	SentNs uint64
}

type netlatStatSlot uint32

const (
	netlatStatSlotSTAT_DESTINATIONS_FULL netlatStatSlot = 0
	netlatStatSlotSTAT_THREADS_FULL      netlatStatSlot = 1
	netlatStatSlotSTAT_UNPAIRED          netlatStatSlot = 2
	netlatStatSlotSTAT_SOCKETS_FULL      netlatStatSlot = 3
	netlatStatSlotSTAT_SLOT_MAX          netlatStatSlot = 4
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	netlatMapDestinations      = "destinations"
	netlatMapInFlight          = "in_flight"
	netlatMapRecvSock          = "recv_sock"
	netlatMapStats             = "stats"
	netlatProgOnTcpRecvmsg     = "on_tcp_recvmsg"
	netlatProgOnTcpRecvmsgRet  = "on_tcp_recvmsg_ret"
	netlatProgOnTcpSendmsg     = "on_tcp_sendmsg"
	netlatVarTargetCgroup      = "target_cgroup"
	netlatVarUnusedDestStats   = "unused_dest_stats"
	netlatVarUnusedDestination = "unused_destination"
	netlatVarUnusedStatSlot    = "unused_stat_slot"
)

// loadNetlat returns the embedded CollectionSpec for netlat.
func loadNetlat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetlatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netlat: %w", err)
	}

	return spec, err
}

// loadNetlatObjects loads netlat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netlatObjects
//	*netlatPrograms
//	*netlatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetlatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetlat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netlatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netlatSpecs struct {
	netlatProgramSpecs
	netlatMapSpecs
	netlatVariableSpecs
}

// netlatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netlatProgramSpecs struct {
	OnTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"on_tcp_recvmsg"`
	OnTcpRecvmsgRet *ebpf.ProgramSpec `ebpf:"on_tcp_recvmsg_ret"`
	OnTcpSendmsg    *ebpf.ProgramSpec `ebpf:"on_tcp_sendmsg"`
}

// netlatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netlatMapSpecs struct {
	Destinations *ebpf.MapSpec `ebpf:"destinations"`
	InFlight     *ebpf.MapSpec `ebpf:"in_flight"`
	RecvSock     *ebpf.MapSpec `ebpf:"recv_sock"`
	Stats        *ebpf.MapSpec `ebpf:"stats"`
}

// netlatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netlatVariableSpecs struct {
	TargetCgroup      *ebpf.VariableSpec `ebpf:"target_cgroup"`
	UnusedDestStats   *ebpf.VariableSpec `ebpf:"unused_dest_stats"`
	UnusedDestination *ebpf.VariableSpec `ebpf:"unused_destination"`
	UnusedStatSlot    *ebpf.VariableSpec `ebpf:"unused_stat_slot"`
}

// netlatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type netlatObjects struct {
	netlatPrograms
	netlatMaps
	netlatVariables
}

func (o *netlatObjects) Close() error {
	return _NetlatClose(
		&o.netlatPrograms,
		&o.netlatMaps,
	)
}

// netlatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type netlatMaps struct {
	Destinations *ebpf.Map `ebpf:"destinations"`
	InFlight     *ebpf.Map `ebpf:"in_flight"`
	RecvSock     *ebpf.Map `ebpf:"recv_sock"`
	Stats        *ebpf.Map `ebpf:"stats"`
}

func (m *netlatMaps) Close() error {
	return _NetlatClose(
		m.Destinations,
		m.InFlight,
		m.RecvSock,
		m.Stats,
	)
}

// netlatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type netlatVariables struct {
	TargetCgroup      *ebpf.Variable `ebpf:"target_cgroup"`
	UnusedDestStats   *ebpf.Variable `ebpf:"unused_dest_stats"`
	UnusedDestination *ebpf.Variable `ebpf:"unused_destination"`
	UnusedStatSlot    *ebpf.Variable `ebpf:"unused_stat_slot"`
}

// netlatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type netlatPrograms struct {
	OnTcpRecvmsg    *ebpf.Program `ebpf:"on_tcp_recvmsg"`
	OnTcpRecvmsgRet *ebpf.Program `ebpf:"on_tcp_recvmsg_ret"`
	OnTcpSendmsg    *ebpf.Program `ebpf:"on_tcp_sendmsg"`
}

func (p *netlatPrograms) Close() error {
	return _NetlatClose(
		p.OnTcpRecvmsg,
		p.OnTcpRecvmsgRet,
		p.OnTcpSendmsg,
	)
}

func _NetlatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netlat_bpfel.o
var _NetlatBytes []byte
