// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package syscount

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type syscountCount struct {
	_       structs.HostLayout
	Entries uint64
	Comm    [16]int8
}

type syscountEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Tgid        uint32
	Pid         uint32
	SyscallNr   int64
	Comm        [16]int8
}

type syscountStatSlot uint32

const (
	syscountStatSlotSTAT_RINGBUF_FULL syscountStatSlot = 0
	syscountStatSlotSTAT_COUNTS_FULL  syscountStatSlot = 1
	syscountStatSlotSTAT__MAX         syscountStatSlot = 2
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	syscountMapCounts          = "counts"
	syscountMapEvents          = "events"
	syscountMapStats           = "stats"
	syscountProgCountSyscalls  = "count_syscalls"
	syscountProgStreamSyscalls = "stream_syscalls"
	syscountVarOffSysEnterId   = "off_sys_enter_id"
	syscountVarTargetCgroup    = "target_cgroup"
	syscountVarTargetSyscall   = "target_syscall"
	syscountVarTargetTgid      = "target_tgid"
	syscountVarUnusedEvent     = "unused_event"
	syscountVarUnusedStatSlot  = "unused_stat_slot"
)

// loadSyscount returns the embedded CollectionSpec for syscount.
func loadSyscount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load syscount: %w", err)
	}

	return spec, err
}

// loadSyscountObjects loads syscount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*syscountObjects
//	*syscountPrograms
//	*syscountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSyscountObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSyscount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// syscountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscountSpecs struct {
	syscountProgramSpecs
	syscountMapSpecs
	syscountVariableSpecs
}

// syscountProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscountProgramSpecs struct {
	CountSyscalls  *ebpf.ProgramSpec `ebpf:"count_syscalls"`
	StreamSyscalls *ebpf.ProgramSpec `ebpf:"stream_syscalls"`
}

// syscountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscountMapSpecs struct {
	Counts *ebpf.MapSpec `ebpf:"counts"`
	Events *ebpf.MapSpec `ebpf:"events"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
}

// syscountVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscountVariableSpecs struct {
	OffSysEnterId  *ebpf.VariableSpec `ebpf:"off_sys_enter_id"`
	TargetCgroup   *ebpf.VariableSpec `ebpf:"target_cgroup"`
	TargetSyscall  *ebpf.VariableSpec `ebpf:"target_syscall"`
	TargetTgid     *ebpf.VariableSpec `ebpf:"target_tgid"`
	UnusedEvent    *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedStatSlot *ebpf.VariableSpec `ebpf:"unused_stat_slot"`
}

// syscountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSyscountObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscountObjects struct {
	syscountPrograms
	syscountMaps
	syscountVariables
}

func (o *syscountObjects) Close() error {
	return _SyscountClose(
		&o.syscountPrograms,
		&o.syscountMaps,
	)
}

// syscountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSyscountObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscountMaps struct {
	Counts *ebpf.Map `ebpf:"counts"`
	Events *ebpf.Map `ebpf:"events"`
	Stats  *ebpf.Map `ebpf:"stats"`
}

func (m *syscountMaps) Close() error {
	return _SyscountClose(
		m.Counts,
		m.Events,
		m.Stats,
	)
}

// syscountVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSyscountObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscountVariables struct {
	OffSysEnterId  *ebpf.Variable `ebpf:"off_sys_enter_id"`
	TargetCgroup   *ebpf.Variable `ebpf:"target_cgroup"`
	TargetSyscall  *ebpf.Variable `ebpf:"target_syscall"`
	TargetTgid     *ebpf.Variable `ebpf:"target_tgid"`
	UnusedEvent    *ebpf.Variable `ebpf:"unused_event"`
	UnusedStatSlot *ebpf.Variable `ebpf:"unused_stat_slot"`
}

// syscountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSyscountObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscountPrograms struct {
	CountSyscalls  *ebpf.Program `ebpf:"count_syscalls"`
	StreamSyscalls *ebpf.Program `ebpf:"stream_syscalls"`
}

func (p *syscountPrograms) Close() error {
	return _SyscountClose(
		p.CountSyscalls,
		p.StreamSyscalls,
	)
}

func _SyscountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscount_bpfel.o
var _SyscountBytes []byte
